# Write a Python program to demonstrate string slicing.
message = "Tops Technologies"
text1 = message[0:4] #Tops 
text2 = message[5:7] #Te
text3 = message[8:]  #hnologies

print(text1)
print(text2)
print(text3)



print("\n")
# Write a Python program that manipulates and prints strings using various string methods.
message = "Python Is a crezy Language"
text1 = message.upper()
text2 = message.lower()
text3 = message.title()

print(text1)
print(text2)
print(text3)