#7.WORKING WITH DICTIONARIES

#1.Write a Python program to update a value in a dictionary. 
#2.Write a Python program to merge two lists into one dictionary using a loop. 

#Practical Examples: 
#(15) Write a Python program to update a value at a particular key in a dictionary. 
#(16) Write a Python program to separate keys and values from a dictionary using keys() and values() methods.
#(17) Write a Python program to convert two lists into one dictionary using a for loop. 
#(18) Write a Python program to count how many times each character appears in a string.
