#7.FUNCTION AND METHOD

#1.Practical Example: 1) Write a Python program to print "Hello" using a string.

text = "Hello"
print(text)

#2.Practical Example: 2) Write a Python program to allocate a string to a variable and print it. 

name = "Hello My Name Ravi"
print(name)

#3.Practical Example: 3) Write a Python program to print a string using triple quotes

code = '''Python Is a Crezy Language'''
print(code)

#4.Practical Example: 4) Write a Python program to access the first character of a string using index value.

company = "Tops Technologies"
print(company[0])

#5.Practical Example: 5) Write a Python program to access the string from the second position onwards using slicing

company = "Tops Technologies"
print(company[2:])


#6.Practical Example: 6) Write a Python program to access a string up to the fifth character.

company = "Tops Technologies"
print(company[:5])

#7.Practical Example: 7) Write a Python program to print the substring between index values 1 and 4. 

message = "Filpkart Is A Commercial Website"
ans = message[1:4]
print(ans)

#8.Practical Example: 8) Write a Python program to print a string from the last character. 

message = "Jio Is a Telecome Company"
ans = message[-1]
print(ans)
#9.Practical Example: 9) Write a Python program to print every alternate character from the string starting from index 1. 

message = "Zerodha Is Trading Account Platform"
ans = message[1::2]
print(ans)