# 1. Write a Python program that prints "Hello, World!".
print("Hello, World!")

# 2. Set up Python on your local machine and write a program to display your name
print("MY NAME RATHORE RAVI I COME FROM TO MODASA.")

# 1. Write a Python program that demonstrates the correct use of indentation, comments, and variables following PEP 8 guidelines.

# This is a comment explaining the following code block
name = "RATHORE RAVI AARYA"
age = 25

# Print the variables
print("Name:", name)
print("Age:", age)
# This program follows PEP 8 guidelines for indentation and variable naming.




# 1. Write a Python program to demonstrate the creation of variables and different data types.
name = "TOPS TECHNOLOGIES"  # String
age = 100  # Integer
height = 5.3  # Float
is_student = True  # Boolean

# Print the variables
print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Is Student:", is_student)
# This program demonstrates the creation of variables with different data types.


