# Practical Example: 4) Write a Python program to access the first character of a string using index value.
message = "Tops Technologies"
print(f"First Letter:{message[0]}")



print("\n")
# Practical Example: 5) Write a Python program to access the string from the second position onwards using slicing.
message = "Zerodha Is Trading Account Platform"
text = message[1:]
print(text)



print("\n")
# Practical Example: 6) Write a Python program to access a string up to the fifth character.
message = "Zomato is a food Deliver Company"
text = message[:5]
print(text)



print("\n")
# Practical Example: 7) Write a Python program to print the substring between index values 1 and 4.
message = "Amazon Is A Commercial Website"
text = message[1:4]
print(text)#maz



print("\n")
# Practical Example: 8) Write a Python program to print a string from the last character.
message = "Filpkart Is A Commercial Website"
text = message[-1]
print(f"Last Character Is:{text}")



print("\n")
# Practical Example: 9) Write a Python program to print every alternate character from the string starting from index 1.
message = "Jio Is a Telecome Company"
text = message[1::2]
print(text)#i saTlcm opn



print("\n")
