# 1. Practical Example 1: How does the Python code structure work?
#STEP 1: PRINT PROGRAM NAME
print("Addition Program")

#STEP 2: TAKE TWO NUMBER
number1 = int (input("Enter the Number1:"))
number2 = int (input("Enter The Number2:"))\

#STEP 3: PERFORM ADDITION PROGRAM
add = number1 + number2

#STEP 4:RESULT
print(f"The Sum Of {number1} and {number2} is: {add}")



# 2. Practical Example 2: How to create variables in Python?
name = "Tops Technologies"  # String
age = 26  # Integer
height = 6.7  # Float
student = True  # Boolean

# Print the variables
print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Is Student:", student)